name: Publish

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-jar:
    runs-on: ubuntu-latest
    needs: get-release-body
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: build UncivServer.jar
        continue-on-error: true
        run: |
          ./gradlew desktop:dist
          ./gradlew desktop:zipLinuxFilesForJar

      - name: Upload JAR
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: ProgramJar
          path: |
            desktop/build/libs/desktop-1.0.jar